### PR TITLE
add --dns-server options as --dns

### PR DESCRIPTION
**Pull request by KatsuragiCSL**
in general accept multiple parameters, easier to add new features in the future

### CODE REVIEW

**Comment by 21y4d** [comment]
Thanks for the effort. I'll review it, test it, and merge it.

**Review by 21y4d — CHANGES_REQUESTED** [review]
Thanks a lot for this excellent effort. I've reviewed the changes, and would love to merged it once a few issues are addressed.

There's an error you made that broke some functions within the script. You replaced all $1 and $2 with $HOST and $TYPE, though sometimes $1 and $2 is used as a function argument, which is sometimes not the same as the script arguments $1 and $2.

For example, the runRecon() function no longer works, as its $2 is actually $reconCommand and not $TYPE. The checkOS() function also is also broken, since it's $1 is $ttl and not $HOST.

So for any affected function just replaced them back with $1 or $2 and so on.

There are also a few small changes necessary before merging:
1. Allow legacy arg syntax, so if --host and --type are not used, $HOST would be set to $1  and $TYPE would be set to $2. We don't want to break the code for people using the old command of running it.
2. if --dns is used, the $host no longer has to go through the IP test at line 552, but go through a URL test instead.
3. The code should only set the main domain as $Host "without sub directories or protocol like http", as nmap does not support that.
4. Perhaps we can set "1.1.1.1" or "8.8.8.8" as default dns-server, when a URL is used and no dns-server is specified "i.e. defaulting to 1.1.1.1 dns-server"

I was able to get all of that working very quickly, but didn't want to commit such changes without proper testing.

I would appreciate it if you can make these changes so we can merge it.

**Comment by KatsuragiCSL** [comment]
Hi @21y4d , I have made the corr. changes and test it with some boxes, seems the problems are fixed now.
Please check the comment of the new commit for detailed changes.

**Comment by 21y4d** [comment]
Thanks a lot for the excellent efforts.
I've reviewed and tested the changes, and everything seems to be working as expected.
Merged with the main branch.

**Pull request merged**
