### PR TITLE
Remove useless use of cat

### PR DESCRIPTION
**Pull request by caribpa**
As a bird, I am not a cat lover, that's why this commit removes the [useless use of cat](https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat) 😿

### CODE REVIEW

**Review by 21y4d — CHANGES_REQUESTED** [review]
Thanks for the effort.
I have always wanted to change such minor things to make the script more efficient, but kept postponing it as it may break the script.

This is what seems to have happened, as the changes broke the script in certain places. The main thing i noticed was in the cmpPorts() and assignPorts() functions, as the grep doesn't seem to like working on two files, and would give a different output than the cat version.

Please fix this if you can, and ensure that all changes give the exact same output, as `cat | grep` and `grep file` may give a slightly different output sometimes, which breaks the script when using advanced string substitution.

**Comment by caribpa** [comment]
Mmm, that's weird. Even [POSIX grep](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/grep.html#tag_20_55_07) defines that grep shall work with more than one file as parameters.

Anyways, I'll revert the `cat` removal in these places as it may very well be an issue with different `grep` implementations.

**Comment by 21y4d** [comment]
yeah perhaps.. it was outputting the IP comma separated, instead of ports comma separated.
I'll also have to double check all the outputs to ensure they are the exact same output and with the same character count, as this may make a difference.
Though from my initial tests 'and logically thinking' it should work just fine.

**Comment by caribpa** [comment]
Reverted `grep <file1> <file2>` to `cat <file1> <file2> | grep`

**Comment by 21y4d** [comment]
Thanks for updating the commit. I've double tested all changed commands, and all seem to give the exact same output, as expected, and the script works just fine.

Thanks for taking the time to enhance the script :)

**Comment by caribpa** [comment]
I'm a bit unsure about how could be achieved with `nmap` (maybe using a `cat <file-with-known-output>` placeholder can work), but have you consider adding test cases so that you don't have to manually check the output of the commands each time a commit/pull-request is made?

**Comment by 21y4d** [comment]
Yeah definitley have to work on a test script. Thanks

**Pull request merged**
